spring.application.name=P06-UnicodeJPA

spring.datasource.url=${PROD_DATABASE_URL}
spring.datasource.username=${PROD_USERNAME}
spring.datasource.password=${PROD_PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

